# serverless.yml

service: BackendServer

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  deploymentBucket:
    name: serverless-deployment-bucketz
  runtime: nodejs16.x
  region: us-east-1

useDotenv: true

functions:
  app:
    handler: index.handler
    url: true